import type { Article } from './types';

export const article1: Article = {
  slug: 'po-neistikimybes',
  title: 'Po neištikimybės: ar galima vėl pasitikėti?',
  category: 'Porų terapija',
  language: 'lt',
  excerpt: 'Kartais po neištikimybės sunkiausia ne pats faktas, kad buvo kitas žmogus, o tai, kad pradedi abejoti tuo, ką laikei savo gyvenimo tiesa.',
  relatedSlugs: ['kai-artumas-tampa-atrama', 'meile-ir-savipakankamumo-iliuzija', 'ar-mums-patogu-kalbeti-apie-seksualuma'],
  publishedAt: '2025-01-15',
  content: [
    'Kartais po neištikimybės sunkiausia net ne pats faktas, kad buvo kitas žmogus. Sunkiausia tampa tai, kad pradedi abejoti tuo, ką iki tol laikei savo gyvenimo tiesa:',
    'Ar tai, ką mes turėjome, buvo tikra?',
    'Ar kai sakei, kad mane myli, tai buvo tiesa?',
    'Ar tada, kai buvome kartu, tu jau buvai kažkur kitur?',
    'Ar aš kažko nemačiau? O gal mačiau, tik nenorėjau matyti?',
    'Žmogus pradeda grįžti į prisiminimus, juos tarsi peržiūrinėti iš naujo: keliones, vakarus, žinutes, kažkokius keistus momentus, kuriems tada gal neteikė reikšmės. Ir kažkur čia sugriūva ne tik pasitikėjimas kitu. Kartais trumpam sugriūva ir pasitikėjimas savimi, savo nuojauta, savo gebėjimu suprasti, kas vyksta santykyje.',
    'Man atrodo, todėl neištikimybė poroje taip stipriai sužeidžia. Ne vien todėl, kad buvo peržengta riba, bet todėl, kad žmogus, kuris buvo mano artimiausias, mano saugumo vieta, tampa tuo, nuo kurio dabar turiu saugotis.',
    'Ir tada prasideda dalykai, kuriuos dažnai matau porų terapijoje. Vienas nori žinoti, klausia, grįžta prie to paties, kartais tikrina telefoną, kartais nori detalių, kartais pyksta dėl to, kas jau buvo aptarta kelis kartus. Kitam tuo metu darosi vis sunkiau. Jis jaučia kaltę, gėdą, spaudimą ir ima gintis: „Aš jau viską pasakiau", „Kiek dar mes apie tai kalbėsime?", „Jeigu nusprendei likti, turime judėti toliau." Arba tiesiog užsidaro.',
    'Ir gaunasi labai skausmingas ratas: kuo labiau vienas ieško saugumo, tuo labiau kitas traukiasi, o kuo labiau jis traukiasi, tuo labiau pirmasis jaučia, kad jo baimė buvo pagrįsta – štai, vėl tavęs nėra tada, kai man tavęs labiausiai reikia.',
    'Terapijoje man dažnai svarbu šitą ratą sulėtinti. Ne skubėti aiškintis, kas teisus, ne skubėti prie „atleidimo" ar klausimo „ar jūs dar būsite kartu". Kartais iki visų šitų klausimų dar reikia prieiti.',
    'Pirmiausia pabandyti suprasti, kas iš tikrųjų vyksta tarp dviejų žmonių. Nes po pykčiu dažnai būna kažkas daug trapesnio: „Aš maniau, kad esu tau ypatingas", „Bijau, kad daugiau niekada negalėsiu tavimi patikėti", „Aš nebežinau, kokia mano vieta tavo gyvenime", „Bijau, kad pasirinkęs tave dar kartą, vėl būsiu sužeistas."',
    'O kitoje pusėje, po gynyba, kartais būna visai ne abejingumas, o daug gėdos: „Man sunku matyti, ką tau padariau", „Aš nežinau, kaip būti su tavo skausmu", „Bijau, kad nuo šiol visą laiką būsiu tik tas žmogus, kuris išdavė."',
    'Man atrodo, vienas svarbiausių momentų terapijoje yra tada, kai pora bent trumpam nustoja kovoti dėl faktų ir pradeda girdėti, kas vienam su kitu iš tikrųjų nutiko.',
    'Čia „atsiprašau" dažnai neužtenka. Ne todėl, kad atsiprašymas nesvarbus, bet todėl, kad žmogui, kuris buvo sužeistas, reikia ne tik žodžių. Reikia naujos patirties su tuo pačiu žmogumi: kad aš galiu pasakyti, kur man skauda, ir tu nepabėgi; kad man nereikia greičiau „susitvarkyti", kad tau būtų lengviau; kad tu gali išbūti su tuo, ką padarei, nesigindamas ir nepaversdamas visko savo kaltės ar gėdos istorija.',
    'Tik vėliau, kai atsiranda truputis daugiau saugumo, galima pradėti žiūrėti ir į kitą dalį. Kas tarp mūsų buvo dar iki neištikimybės? Kur mes pradėjome vienas kitą prarasti? Apie ką nustojome kalbėtis? Kur vienas iš mūsų liko vienas, nors abu vis dar gyvenome kartu?',
    'Man tai nėra bandymas pateisinti neištikimybę. Atsakomybė už neištikimybę priklauso tam, kuris pasirinko taip pasielgti. Bet suprasti, kas vyko santykyje, nėra tas pats, kas pateisinti tai, kas buvo padaryta.',
    'Jeigu pora nusprendžia likti kartu, man atrodo, neužtenka tiesiog „grįžti į normalų gyvenimą". Ir gal net nėra kur grįžti. Tai, kas įvyko, jau yra jų istorijos dalis.',
    'Kartais tenka kurti kitokį santykį: atviresnį, gal mažiau mandagų, tokį, kuriame galima pasakyti apie pyktį, vienatvę, seksualinį atitolimą ar baimę daug anksčiau, nei visa tai pradeda gyventi kažkur už santykio ribų.',
    'Ir tada klausimas jau nebe tik „ar galiu tau atleisti?". Kartais svarbesnis tampa kitas: ar mes galime sukurti tokį santykį, kuriame vėl būtų galima rizikuoti artumu?',
    'Man atrodo, pasitikėjimas po neištikimybės dažniausiai negrįžta kaip vienas didelis sprendimas. Jis grįžta mažais momentais: aš kreipiuosi į tave ir tu lieki, aš parodau, kur man skauda, ir tu nenusisuki, aš bijau ir man nereikia apsimesti, kad jau nebebijau.',
    'Šitoje vietoje ir prasideda naujas santykis: ne tada, kai tai, kas įvyko, pagaliau pamirštama, o tada, kai su tuo, kas įvyko, jau galima būti kartu.',
  ],
};

export const article2: Article = {
  slug: 'ar-terapija-turi-nuraminti',
  title: 'Ar terapija turi nuraminti? Apie nerimą ir pokytį',
  category: 'Psichoterapija',
  language: 'lt',
  excerpt: 'Kartais terapijoje žmogus pasako, kad po paskutinio susitikimo pradėjo jausti daugiau nerimo. Ar terapija tikrai turi nuraminti?',
  relatedSlugs: ['kai-norisi-kad-kas-nors-pasakytu-kaip-gyventi', 'ar-as-esu-suauges', 'kai-rysys-gydo'],
  publishedAt: '2025-02-01',
  content: [
    'Kartais terapijoje žmogus pasako: „Jaučiu frustraciją. Vaikštau pas tave, o po paskutinio susitikimo pradėjau jausti daugiau nerimo. Ypač apie pinigus. Atrodo, prieš tai apie tai tiek negalvojau, o dabar terapija tuos klausimus iškėlė ir nebegaliu taip ramiai su tuo būti. Net pradėjau domėtis, ar normalu po terapijos jaustis blogiau nei prieš ją."',
    'Sėdžiu ir galvoju: ar terapija tikrai turi nuraminti? Ar jos tikslas yra padaryti, kad žmogui kuo greičiau būtų lengviau?',
    'O gal kartais ji kaip tik sujudina tai, ką ilgą laiką pavyko apeiti, atidėti, paaiškinti sau ar tiesiog nepastebėti. Kartais pradedi matyti savo elgesio modelius ir tada jų jau nebeišeina taip lengvai nematyti.',
    'Ir čia man kyla klausimas, ar žmogus terapijoje ieško nuraminimo, ar vis dėlto pokyčio. Turbūt ir vieno, ir kito. Tik pats pokytis dažnai nėra labai ramus.',
    'Su šitais klausimais gyvenu ir pats. Ką reiškia komfortas? Ką reiškia bijoti? Ar nerimas visada yra kažkas, ką reikia kuo greičiau pašalinti?',
    'Mes juk dažnai puikiai žinome, kad toks pats elgesys atves į labai panašią vietą. Elgiuosi taip pat, gaunu panašų atsaką, ir vis tiek kartoju, nes tai pažįstama.',
    'Kartais pagalvoju, kad tai prasideda labai anksti. Jei vaikystėje į mano klausimus buvo greitai atsakoma, gal net nepaliekant vietos smalsumui ar nežinojimui, tai ir suaugęs galiu ieškoti žmogaus, kuris pasakys, kaip reikia gyventi. Kur eiti. Kas teisinga. Tarsi būčiau valtis, į kurią kažkas turi įlipti ir parodyti kryptį.',
    'Mes ir vaikams dažnai labai greitai atsakome apie meilę, Dievą, mirtį, gyvenimą. Nors patys turbūt daug ko nežinome.',
    'Ketverių metų vaikas klausia: „Iš kur aš atsiradau?" Biologija duoda vieną atsakymą, religija kitą. Bet ar klausimas tuo tikrai baigiasi?',
    'Iš kur aš atsiradau? Kodėl esu? Kas apskritai yra gyvenimas?',
    'Gal dalį tokių klausimų tiesiog nešomės su savimi. Tik mums labai sunku nežinoti.',
    'Ir terapijoje, man atrodo, yra panašiai. Norisi atsakymo. Norisi, kad kas nors pasakytų, ką daryti. Norisi, kad nerimas dingtų.',
    'Grįžtu prie žmogaus, kuris kalba apie pinigus ir nerimą. Sakau jam maždaug taip:',
    '„Tu daugiau nei dvidešimt metų gyvenai tam tikru būdu. O dabar staiga aiškiau pamatai, kad ten, kur esi, yra nemažai nerimo. Ar nori, kad jis tiesiog dingtų? Net jeigu kišenėje nėra pinigų? Kad galėtum ramiai sėdėti po medžiu ir nieko dėl to nejausti? O gal dalis šito nerimo kažką tau sako ir gal net stumia kažką keisti, kurti, prisiimti daugiau atsakomybės už savo gyvenimą?"',
    'Aš nemanau, kad kančią reikia romantizuoti. Kančią reikia mažinti, bet kartais nuolatinis noras kuo greičiau pasijausti geriau irgi gali tapti tuo pačiu senu modeliu.',
    'Mes labai daug prie ko priprantame: prie nuovargio, miego trūkumo, darbo iki išsekimo, įtampos, santykių, kuriuose per daug savęs atiduodame. Prie gyvenimo, kuriame vis mažiau mūsų pačių – po kiek laiko tai tampa norma.',
    'Dabartinė visuomenė pilna perdegimo, depresijos, miego deprivacijos, net atsipalaidavimas dažnai tampa ne poilsiu, o būdu save trumpam pamiršti. „Išsitaškyti", atsijungti, negalvoti, kad tik nereikėtų susitikti su tuo, kas laukia viduje.',
    'Tada atrodo: štai dabar aš gyvas.',
    'Bet man vis kyla klausimas, ar tikrai.',
    'Man gyvas gyvenimas turbūt labiau prasideda tada, kai nustoji nuo savęs bėgti. Kai gali sau pripažinti, kad kažkas nebetinka, kad skauda, pavargai.',
    'Kartais pamatai, jog tai, kas ilgai atrodė normalu, iš tikrųjų jau seniai vargina. Jog beveik nebesiilgi, kad darbas užima per daug vietos, kad bandydamas prisitaikyti prie kitų kažkur pameti save.',
    'Ir tada ne visada aišku, ką su tuo daryti, bet bent jau nebegali apsimesti, kad viskas gerai.',
    'Tada nerimas gali būti ne tik tai, ką reikia išjungti. Kartais jis parodo, kad kažkas negerai. Kad kažkur gyvenu ne taip, kaip iš tiesų noriu.',
    'Ir čia turbūt atsiranda vienas iš terapijos paradoksų: ateiname, nes norime mažiau kentėti, bet kartais pirmiausia pradedame daug aiškiau matyti, kur ir kiek jau kenčiame.',
    'Gal terapija ne visada iškart nuramina: kartais ji tiesiog nebeleidžia taip lengvai nuo savęs pabėgti.',
    'Ir tada lieka klausimas: ar aš iš tikrųjų taip noriu gyventi? Ar visgi aš noriu dabar sustoti?',
  ],
};

export const article3: Article = {
  slug: 'kai-norisi-kad-kas-nors-pasakytu-kaip-gyventi',
  title: 'Kai norisi, kad kas nors pasakytų, kaip gyventi',
  category: 'Psichoterapija',
  language: 'lt',
  excerpt: 'Dažnai žmonės į terapiją kreipiasi tada, kai jų gyvenime kažkas pasikeičia. Ir tada atsiranda klausimai, kuriuos terapijoje girdžiu gana dažnai: pasakykite, kaip man gyventi?',
  relatedSlugs: ['ar-terapija-turi-nuraminti', 'ar-as-esu-suauges', 'kai-rysys-gydo'],
  publishedAt: '2025-02-15',
  content: [
    'Dažnai žmonės į terapiją kreipiasi tada, kai jų gyvenime kažkas pasikeičia. Kartais tai būna santykių krizė, išsiskyrimas, netektis, darbo pakeitimas ar kita situacija, po kurios atrodo, kad staiga praradai žemę po kojomis.',
    'Kartais išoriškai lyg ir nieko ypatingo neįvyksta, tačiau žmogus kažkuriuo momentu pajunta, kad taip, kaip gyveno iki šiol, toliau judėti nebegali.',
    'Ir tada atsiranda klausimai, kuriuos terapijoje girdžiu gana dažnai: pasakykite, kaip man gyventi? Kaip suprasti, ko aš noriu? Kas man iš tikrųjų svarbu? Ar man likti santykiuose, ar išeiti? Ką man daryti?',
    'Ir, žinoma, norisi atsakymo. Geriausia greito, aiškaus ir tokio, kurį jau rytoj būtų galima pradėti taikyti.',
    'Man atrodo, kad tokie klausimai bent akimirkai glumina ne vieną terapeutą. Galvoje gali pradėti suktis visi mokymai, perskaitytos teorijos, klinikinė patirtis, savo gyvenimo išmintis ir noras žmogui kuo greičiau padėti.',
    'Kartais ir pats pagaunu save galvojant: na gerai, o ką aš čia galėčiau pasakyti?',
    'Tačiau tuomet atsiranda kitas klausimas.',
    'Ar aš iš tikrųjų žinau, kaip kitam žmogui reikia gyventi? Ar aš pats visą laiką žinau, kaip man gyventi? Ir ar svarbiausi mano gyvenimo atsakymai atsirado todėl, kad kažkas juos man pasakė?',
    'Turbūt ne visada.',
    'Mes gyvename kultūroje, kurioje greitas ir efektyvus sprendimas tapo beveik savaimine vertybe. Jei kažkas neveikia, reikia metodo. Jei jauti nerimą, reikia technikos. Jei nežinai, ko nori, reikia klausimyno, kurso ar penkių žingsnių sistemos.',
    'Internetas pilnas turinio apie tai, kaip per savaitę atpažinti savo poreikius, per mėnesį pakeisti santykius ar per vieną intensyvią dieną patirti „visišką transformaciją".',
    'Nesakau, kad patarimai yra blogai. Kartais konkretus patarimas žmogui iš tiesų padeda, ypač krizėje.',
    'Bet man įdomu, kas nutinka, kai psichologinę pagalbą pradedame vertinti pagal tą pačią logiką kaip ir kitus produktus: kiek greitai suveiks, kiek sesijų reikės, kada turėsiu rezultatą ir kada problema bus „sutvarkyta".',
    'Psichoanalitikas Stijnas Vanheule rašo apie protokolinę terapijos logiką, kai žmogaus sunkumas apibrėžiamas kaip simptomas, simptomui parenkama technika, o terapijos sėkmė matuojama tuo, kaip greitai simptomas sumažėjo.',
    'Žinoma, simptomų mažėjimas yra svarbus. Jei žmogus negali miegoti, jį nuolat ištinka panikos atakos ar jis gyvena stipriame nerime, būtų keista sakyti, kad tai nesvarbu.',
    'Tačiau kartu kyla klausimas, ar simptomas visada yra tik tai, ką reikia pašalinti.',
    'Terapija siūlo į jį žiūrėti ir kaip į tai, kas kažką apie žmogų pasako: apie jo istoriją, santykius, pasikartojimus, konfliktus ir tai, ko jis dar negali iki galo įvardyti.',
    'Čia man įdomi ir Jacques\'o Lacano mintis apie tai, kaip apskritai susiformuoja tai, ką vadiname savo „aš".',
    'Kalbėdamas apie veidrodžio stadiją, Lacanas aprašo vaiką, kuris savo vientisumą pirmiausia pamato išorėje, veidrodyje, Kito žmogaus žvilgsnyje ir Jo žodžiuose.',
    'Man ši mintis svarbi kaip priminimas, kad mūsų supratimas apie save nuo pat pradžių nėra sukuriamas vien mūsų pačių. Mes save pamatome ir per kitus, per tai, ką apie mus sakė tėvai, ką jie mumyse pastebėdavo, už ką gyrė, kuo nusivildavo.',
    'Vėliau prie to prisideda mokykla, santykiai, profesija, kultūra ir visuomenė.',
    'Todėl iš pirmo žvilgsnio labai paprastas klausimas „ko aš noriu?" kartais pasirodo esantis visai nepaprastas.',
    'Kiek tame mano noro yra mano? O kiek ten yra tėvų lūkesčio, šeimos istorijos, supratimo, ką reiškia būti sėkmingam, stipriam, geru partneriu, geru tėvu ar produktyviu žmogumi?',
    'Dany-Robert Dufour, Charles Melman, rašantys apie neoliberalios kultūros poveikį žmogui, atkreipia dėmesį į tai, kad šiuolaikinis žmogus vis labiau tampa savotišku projektu, kurį reikia nuolat tobulinti.',
    'Geresnis kūnas, geresni santykiai, daugiau produktyvumo, daugiau sąmoningumo, geresnė karjera ir, žinoma, geresnė savo versija.',
    'O jeigu viduje vis tiek kažkas negerai, labai lengva pagalvoti, kad dar nepakankamai su savimi dirbau.',
    'Man tai svarbu ir terapijoje.',
    'Žmogus gali ateiti ieškodamas atsakymo į klausimą „ką man daryti?", bet po kurio laiko gali paaiškėti, kad daug įdomesnis klausimas yra, kodėl jis taip stipriai nori, kad kažkas kitas žinotų atsakymą už jį.',
    'Terapeutas tikrai gali turėti daug žinių, matyti tam tikrus santykių modelius, pasikartojimus, gynybas ir kartais pasiūlyti labai konkrečių dalykų.',
    'Bet jeigu terapijoje nuolat tampu tuo, kuris geriau žino, ką žmogui daryti, man kyla etinis klausimas: ką tuomet žmogus išmoksta?',
    'Klausyti savęs ar klausyti manęs?',
    'Dažnai klientams sakau: jums prireikė nemažai metų ateiti iki šito gyvenimo taško. Kartais dvidešimt, trisdešimt ar keturiasdešimt metų.',
    'Ar tikrai galima tikėtis, kad tai, kas formavosi taip ilgai, bus išspręsta per kelias savaites?',
    'Kaip būtų gera, jeigu būtų galima. Aš pats norėčiau kai kuriems savo gyvenimo klausimams gauti atsakymą per kelias dienas.',
    'Bet kol kas tokio būdo nežinau.',
    'Todėl turbūt tai, ką galiu pasiūlyti terapijoje, nėra greitas atsakymas.',
    'Greičiau tai vieta, kurioje galima kurį laiką neskubėti atsakyti ir pradėti tyrinėti, kodėl tam tikri dalykai gyvenime kartojasi, kieno balsu kalbu sakydamas „aš privalau", ko bijau netekti, jei pasirinksiu kitaip, ir ko iš tikrųjų noriu tada, kai bent trumpam nustoju ieškoti žmogaus, kuris tai pasakytų už mane.',
  ],
};
