import type { Article } from './types';

export const article4: Article = {
  slug: 'ar-as-esu-suauges',
  title: 'Ar aš esu suaugęs?',
  category: 'Psichoterapija',
  language: 'lt',
  excerpt: 'Dabartinėje psichologinėje kultūroje kartais matau du kraštutinumus. Vienas – esu stiprus, nepriklausomas. Kitas – mano „vidinis vaikas" toks gležnas. O kur tarp jų yra suaugęs žmogus?',
  relatedSlugs: ['kai-norisi-kad-kas-nors-pasakytu-kaip-gyventi', 'meile-ir-savipakankamumo-iliuzija', 'kai-rysys-gydo'],
  publishedAt: '2025-03-01',
  content: [
    'Dabartinėje psichologinėje kultūroje kartais matau du kraštutinumus.',
    'Viename jų esu stiprus, nepriklausomas, žinau, ką darau, man kitas nereikalingas, viską galiu išspręsti pats.',
    'Kitame – mano „vidinis vaikas" toks gležnas ir pažeidžiamas, kad šalia turi būti labai jautrus žmogus, kuris manęs neužgautų, nesukeltų per daug nepatogumo ar neprisiliestų prie to, kas manyje skauda.',
    'Ir vis pagalvoju, o kur tarp šių dviejų kraštutinumų yra suaugęs žmogus?',
    'Praėjusią savaitę pas mane lankėsi draugas, psichoterapeutas ir Niujorko geštalto instituto treneris.',
    'Kaip dažnai nutinka susitikus terapeutams, pokalbis nuo visai paprastų dalykų – arbatos, maisto ragavimo, kasdienybės – kažkaip pereina prie terapijos, santykių, gyvenimo ir kitų gilesnių klausimų.',
    'Pasakodamas apie savo darbą jis prisiminė vieną situaciją, be atpažįstamų kliento detalių.',
    'Maždaug keturiasdešimties metų vyras bijojo prieiti prie savo paauglio sūnaus ir iš tikrųjų su juo susitikti. Bijojo jo reakcijos, atstūmimo, to, kad sūnus gali pasakyti kažką skaudaus.',
    'Draugas jo paklausė maždaug taip:',
    '„Bet tu jau suaugęs. Ką jis tau gali padaryti? Užgauti? Įskaudinti? Kaip tu galėsi susitikti su juo kaip su kitu žmogumi, jeigu taip bijai būti jo paliestas?"',
    'Tuo metu ta istorija, rodos, tiesiog praslydo pro ausis. Kalbėjomės toliau.',
    'Bet paskui ji pradėjo vis sugrįžti, ypač galvojant apie artimus santykius.',
    'Pastebiu, kad ir pats kartais bijau tyrinėti tam tikras temas su mylimu žmogumi. Kažką pasakyti iki galo, paklausti to, ko iš tikrųjų noriu paklausti, parodyti savo norą.',
    'Nes ji gali nesuprasti. Gali atsakyti visai ne taip, kaip tikiuosi. Gali užgauti.',
    'Ir, žinoma, kartais užgauna net ne vien tas žmogus, kuris dabar yra priešais mane. Jo žodžiai gali paliesti daug senesnes patirtis – santykius su tėvais, artimaisiais, ankstesnius ryšius, vietas, kur kažkada buvai neišgirstas, nesuprastas ar paliktas vienas su tuo, ką jautei.',
    'Man atrodo labai svarbu tai pažinti.',
    'Čia psichoterapija gali duoti daug – pradedi geriau suprasti, kas su tavimi vyksta, kur tavo jautrios vietos, iš kur jos atsirado.',
    'Bet vis dažniau sau užduodu kitą klausimą: gerai, aš jau žinau, kodėl man skauda. O ką dabar su tuo darysiu?',
    'Nes yra vienas dalykas suprasti savo pažeidžiamumą, o visai kitas – pradėti tikėtis, kad kitas žmogus prie jo niekada neprisilies.',
    'Nežinau, ar artimame santykyje tai apskritai įmanoma.',
    'Kuo žmogus man svarbesnis, tuo daugiau galios jis turi mane pradžiuginti, bet kartu ir nuvilti, nesuprasti ar įskaudinti.',
    'Gal čia ir atsiranda drąsos klausimas.',
    'Ne tokios drąsos, kai bandau būti „kietas" ir įrodyti, kad man niekas nesvarbu.',
    'Greičiau gebėjimo pasilikti santykyje žinant, kad ne viską jame kontrolioju.',
    'Pasakyti kažką svarbaus net nežinant, kaip tai bus priimta. Pasakyti, kad man nepatogu ar kad aš noriu kitaip, ir kartu leisti kitam atsakyti savaip.',
    'Kartais išgirsti tai, ko visai nenorėjau išgirsti, ir nepulti iš karto nei trauktis, nei versti kitą pasikeisti.',
    'Šitoje vietoje man kyla ir tam tikra abejonė dėl kai kurių šiandien labai populiarių psichologinių sąvokų.',
    '„Vidinis vaikas", „trigeriai", „pažeidžiamumas", „saugi erdvė" gali būti labai naudingi žodžiai. Jie padeda pamatyti tai, ko anksčiau savyje gal net nepastebėdavome.',
    'Tačiau kartais jie gali pradėti ir riboti, jeigu iš supratimo, kad esu jautrus, pamažu pereinu prie įsitikinimo, jog aplinkiniai turi būti taip sutvarkyti, kad aš niekada nepatirčiau per didelio nepatogumo.',
    'Terapijoje man todėl svarbu ne vien padėti žmogui daugiau jausti.',
    'Jausmai, kūno reakcijos, jautrumas yra puikūs signalai, padedantys suprasti, kur aš esu ir kas su manimi vyksta.',
    'Bet po klausimo „ką aš jaučiu?" man ne mažiau svarbus kitas:',
    '„Ką aš su tuo darysiu?"',
    'Nes atsakomybė už savo gyvenimą nereiškia, kad turiu nustoti būti jautrus.',
    'Greičiau priešingai – galiu žinoti, kad bijau, kad man skauda, kad kažkas manyje labai nori pasitraukti ir kartu spręsti, kaip noriu elgtis.',
    'Čia prisimenu Roberto Resnicko mintį:',
    '„Jeigu santykyje iš tikrųjų nepasirodai toks, koks esi, niekada negali sužinoti, ar jūs iš tiesų derate. Santykiai ir santuokos, kuriuose save nuolat kontroliuojame ir pritaikome, turi esminę problemą: jeigu mano santykis veikia tik tada, kai manęs jame iš tikrųjų nėra, tuomet jis praranda pačią savo prasmę."',
    'Man šita mintis vis sugrįžta.',
    'Jeigu nuolat nueinu nuo savo noro tam, kad būčiau patogus kitam, kažkuriuo metu santykyje lieka vis mažiau manęs.',
    'Bet jeigu bandau pakeisti kitą taip, kad jis būtų patogus man ir neliestų mano jautrių vietų, tuomet lieka vis mažiau jo.',
    'Gal todėl tikras santykis neišvengiamai turi rizikos.',
    'Aš ateinu su tuo, kas esu, kitas ateina su tuo, kas yra jis, ir mes nežinome iš anksto, kas iš šio susitikimo išeis.',
    'Ir gal būti suaugusiam nereiškia pagaliau tapti tokiam stipriam, kad niekas nebegalėtų manęs užgauti.',
    'Man vis labiau atrodo, kad suaugystė yra gebėjimas žinoti, jog galiu būti užgautas, nuviltas ar nesuprastas, ir vis dėlto neprarasti savo balso, savo pasirinkimo ir atsakomybės už tai, kaip kuriu savo gyvenimą bei santykį.',
  ],
};

export const article5: Article = {
  slug: 'meile-ir-savipakankamumo-iliuzija',
  title: 'Meilė ir savipakankamumo iliuzija',
  category: 'Santykiai',
  language: 'lt',
  excerpt: 'Vakar klausiausi Slavojaus Žižeko, filosofo, kurio mintys mane dažnai sujudina. Jo kalbėjimas aštrus, kartais radikalus, nevengiantis nepatogių formuluočių.',
  relatedSlugs: ['po-neistikimybes', 'kai-artumas-tampa-atrama', 'ar-mums-patogu-kalbeti-apie-seksualuma'],
  publishedAt: '2025-03-15',
  content: [
    'Vakar klausiausi Slavojaus Žižeko, filosofo, kurio mintys mane dažnai sujudina, nors ne visada su jomis sutinku.',
    'Jo kalbėjimas aštrus, kartais radikalus, nevengiantis nepatogių formuluočių.',
    'Klausydamasis jo vėl pradėjau galvoti apie meilę ir narcisistinę visuomenę, kurioje gyvename.',
    'Žodis „narcisizmas" šiandien mirga spaudoje ir socialiniuose tinkluose: „gyvenu su narcizu", „kaip atpažinti narcizą", „kaip nuo jo apsisaugoti".',
    'Tačiau grįžus prie Freudo tekstų narcisizmas pasirodo ne vien kaip diagnozė ar charakterio trūkumas.',
    'Freudas kalba ir apie pirminį narcisizmą: ankstyvą žmogaus raidos būvį, kuriame vaiko pasaulis pirmiausia sukasi aplink jo paties poreikius.',
    'Turintieji vaikų šį reiškinį tikriausiai yra matę ne kartą. Vaikas gali griebti žaislą iš kito rankų, kovoti dėl mažiausio daikto, reikalauti, kad pasaulis iš karto atsilieptų į jo norą.',
    'Kitam žmogui ir jo norams dar tik mokomasi suteikti vietos.',
    'Kartais atrodo, kad šios pozicijos pėdsakų lieka ne tik asmeniniuose santykiuose, bet ir politiniame gyvenime.',
    'Mano tiesa turi tapti vienintele tiesa, mano kultūra yra svarbiausia, mano pasaulio vaizdas – privalomas kitiems.',
    'Panašus į mane tampa mylimas, o kitoks – pavojingas, nuvertinamas ar net naikinamas.',
    'Tačiau augdamas vaikas pamažu atranda, kad egzistuoja Kitas.',
    'Kitas turi savus jausmus, norus, ribas ir savo istoriją. Jis nėra vien mano poreikių tęsinys.',
    'Man atrodo, kad iš tikrųjų pamatyti kito unikalumą reiškia ne vien ieškoti panašumo.',
    'Tai reiškia leisti sau būti paliestam kitos būties, to, ko negaliu iki galo paaiškinti, numatyti ar kontroliuoti.',
    'Žižekas yra pasakęs, kad mylimam žmogui gali būti pavojinga būti mylimam ne už tai, kas jis yra, bet todėl, kad atitinka idealą.',
    'Ši mintis man atrodo ypač aktuali šiandien.',
    'Meilė kartais ima priminti vartojimą: susikuriame savybių sąrašą, ieškome „idealaus atitikmens", o žmogui jo neatitikus grįžtame į „Tinder", „Bumble" ar kitą platformą.',
    'Next.',
    'Galbūt kitas variantas bus tinkamesnis.',
    'Bet ar tuomet iš tikrųjų sutinkame kitą žmogų?',
    'O gal ieškome veidrodžio, kuris patvirtintų mūsų pačių idealą?',
    'Žižekas provokuojančiai sako: „Love is an extremely violent act."',
    'Meilė yra itin smurtinis aktas.',
    'Ne todėl, kad meilė turėtų žeisti ar naikinti kitą.',
    'Veikiau todėl, kad ji suardo mūsų įprastą pasaulio tvarką. Žmogus gyvena savo gyvenimą, turi įpročius, planus, tam tikrą vaizdą apie save, ir staiga atsiranda Kitas, kuris visa tai pakeičia.',
    'Meilė įsiveržia į savipakankamumo iliuziją.',
    'Ji primena, kad ne viską galiu kontroliuoti, o mano gyvenimas nebėra vien mano paties projektas.',
    'Tai gali būti stiprus smūgis narcisistinei mūsų daliai.',
    'Tada gali kilti noras pakeisti kitą pagal savo paveikslą, įtikinti, nugalėti, priversti prisitaikyti.',
    'Kartais darome priešingai – patys perimame kito norus ir savybes, kad tik neprarastume ryšio.',
    'Abiem atvejais gali likti tas pats siekis – išlaikyti kontrolę ir išvengti patirties, kad kitas iš tikrųjų mane veikia.',
    'O ar meilė apskritai paklūsta kontrolei?',
    'Šią savaitę supervizijų grupė su Ximo Tárrega ir jo tekstai dar kartą paskatino galvoti apie tai, kad nesame atskiros, uždaros salos.',
    'Nuo pat gimimo tampame savimi santykyje, per Kito žvilgsnį, balsą, prisilietimą ir atsaką.',
    'Kitas mane ne tik mato.',
    'Jo žvilgsnyje aš pats imu jausti, kad esu.',
    'Narcisistinės kultūros paradoksas tas, kad ji žada laisvę per savipakankamumą: man nieko nereikia, aš pats galiu viskuo pasirūpinti, niekas neturi teisės manęs trikdyti.',
    'Tačiau visiška nepriklausomybė kartais tampa ne stiprybe, o gynyba nuo galimo nusivylimo, atstūmimo ir skausmo.',
    'Brandus santykis nėra nei susiliejimas, nei visiškas atsiribojimas.',
    'Tai tarpusavio priklausomybė, kurioje galime išlikti du skirtingi žmonės ir kartu pripažinti:',
    'Man tavęs reikia. Ne tam, kad užpildytum visas mano spragas, bet todėl, kad santykyje su tavimi tampu tuo, kuo vienas negalėčiau būti.',
    'Tu esi, ir aš liudiju tavo buvimą.',
    'Aš esu, nes tavo žvilgsnyje tampu matomas.',
  ],
};
