import type { Article } from './types';

export const article9: Article = {
  slug: 'kai-rysys-gydo',
  title: 'Kai ryšys gydo: apie terapinį santykį, pažeidžiamumą ir ryšį',
  category: 'Psichoterapija',
  language: 'lt',
  excerpt: 'Gyvenime mes susiduriame su įvairiais santykiais. Kiekvienas jų turi savitą būdą, kaip mezgame ryšį su kitu. Ar tikras artumas prasideda ten, kur po truputį išdrįstame būti pažeidžiami?',
  relatedSlugs: ['psichoterapeuto-uzrasai', 'ar-as-esu-suauges', 'kai-artumas-tampa-atrama'],
  publishedAt: '2025-05-15',
  content: [
    'Gyvenime mes susiduriame su įvairiais santykiais: draugo, brolio, sesers, tėvų, mylimo žmogaus.',
    'Kiekvienas jų turi savitą būdą, kaip mezgame ryšį su kitu.',
    'Martinas Buberis kalbėjo apie santykį Aš–Tu, tokį susitikimą, kuriame kitas žmogus nėra tik funkcija, vaidmuo ar tas, kuris turi patenkinti mūsų poreikius.',
    'Tai ryšys, kuriame kitą sutinkame kaip gyvą žmogų, o patys galime būti matomi.',
    'Atrodo paprasta – tiesiog matyti kitame žmogų.',
    'Bet, tiesą sakant, man atrodo, kad tai vienas sunkiausių dalykų santykiuose.',
    'Į terapiją dažnai ateinama su sunkumais kurti artimus santykius: pasitikėti, atsiverti, išbūti meilėje, likti ryšyje net tada, kai skauda.',
    'Mes visi trokštame artumo, tačiau neretai slepiamės po šarvais, kurie saugo nuo galimo atstūmimo, įskaudinimo ar nusivylimo.',
    'Dažnai girdžiu:',
    '„Aš nerodau kitiems, kad esu pažeidžiamas, nes mane įskaudins."',
    '„Aš nebūnu atviras, nes tuo gali pasinaudoti."',
    '„Jeigu parodysiu, kad man skauda, būsiu silpnas."',
    'Ir vis dėlto ryšys reikalauja nuoširdumo.',
    'Kad ir kaip paradoksaliai tai skambėtų, būtent savo trapume mes galime priartėti prie kito.',
    'Ne kaukėje, ne šaltyje, ne nuolatinėje gynyboje, o ten, kur po truputį pasirodo tikras žmogus.',
    'Byung-Chul Han knygoje „Eroso agonija" kalba apie tai, kad tikras susitikimas su Kitu nyksta tada, kai kitą pradedame matyti tik per savo poreikius, patogumą ar naudą.',
    'O gyvas ryšys prasideda ten, kur kitas nėra tik pritaikomas sau, bet sutinkamas kaip Kitas.',
    'Terapinis santykis ypatingas tuo, kad jame žmogus gali po truputį patirti:',
    '„Aš galiu būti atviras ir nebūti pasmerktas."',
    '„Aš galiu kalbėti apie tai, kas man skauda, ir nebūti atstumtas."',
    '„Aš galiu būti pažeidžiamas ir vis tiek likti ryšyje."',
    'Kartais klientai sako:',
    '„Aš noriu būti toks atviras ne tik čia, su tavimi, bet ir išėjęs – su savo mylimu žmogumi, draugu, artimaisiais."',
    'Tada klausiu:',
    '„O kas tau čia padeda būti atviram?"',
    'Ir dažnai atsakymas labai paprastas:',
    '„Mane girdi."',
    '„Manęs nevertina."',
    '„Aš galiu būti toks, koks esu."',
    'Mane tokie žodžiai visada paliečia.',
    'Iš savo gyvenimo patirties taip pat žinau, kaip gera būti išgirstam mylimo žmogaus, palaikytam draugo, pamatytam ne per kaltinimą ar vertinimą, o per buvimą kartu.',
    'Bet dažnai toks ryšys atsiranda tik tada, kai pats po truputį rizikuoji atsiverti.',
    'Terapijoje mes mokomės ne tik kalbėti apie emocijas, bet ir būti santykyje su jomis.',
    'Pastebėti, kas vyksta po mūsų gynybomis, po noru pasitraukti, po šarvais, kuriuos ilgai laikėme savo apsauga.',
    'Galbūt klausimas yra ne tik:',
    '„Kaip man būti stipriam?"',
    'Bet ir:',
    '„Kur galiu būti pakankamai saugus, kad parodyčiau savo trapumą?"',
    '„Su kuo galiu būti ne tobulas, o tikras?"',
    '„Kada jaučiuosi matomas, girdimas ir priimamas?"',
    'Ko gero tikras artumas ir prasideda ten, kur po truputį išdrįstame būti pažeidžiami.',
  ],
};

export const article10: Article = {
  slug: 'kai-artumas-tampa-atrama',
  title: 'Kai artumas tampa atrama',
  category: 'Santykiai',
  language: 'lt',
  excerpt: 'Kartais poros ateina į terapiją ne todėl, kad meilė baigėsi, o todėl, kad jos nebežino, kaip vienas kitą pasiekti. Galbūt tikras artumas prasideda ten, kur autonomija ir ryšys ne kovoja, o maitina vienas kitą.',
  relatedSlugs: ['po-neistikimybes', 'meile-ir-savipakankamumo-iliuzija', 'kai-rysys-gydo'],
  publishedAt: '2025-06-01',
  content: [
    'Kartais poros ateina į terapiją ne todėl, kad meilė baigėsi, o todėl, kad jos nebežino, kaip vienas kitą pasiekti.',
    'Išoriškai tai gali atrodyti kaip konfliktai dėl buities, pinigų, vaikų, laiko ar dėmesio.',
    'Tačiau po tais ginčais dažnai slepiasi daug jautresni klausimai:',
    'ar aš tau dar svarbus?',
    'Ar tu mane matai?',
    'Ar galiu prie tavęs būti savimi?',
    'Ar tu vis dar esi mano žmogus?',
    'Šiuolaikiniame pasaulyje daug kalbame apie autonomiją, ribas, savęs pažinimą, galios žaidimus ir konfliktų sprendimą.',
    'Visa tai svarbu.',
    'Tačiau kartais atrodo, kad meilės, švelnumo ir gyvo tarpusavio susitikimo tema lieka kažkur paraštėse.',
    'Mes ilgimės ryšio, bet gyvename kultūroje, kurioje vis daugiau svorio įgyja individualizmas.',
    'Tarsi žmogus turėtų pirmiausia „susitvarkyti save", tapti visiškai savarankiškas, nepriklausomas, aiškiai žinantis savo ribas.',
    'Bet kur tada lieka vietos santykiui, kuris ne riboja, o maitina?',
    'Prieraišumo teorija primena, kad poreikis turėti artimą ir saugų Kitą nėra tik vaiko poreikis.',
    'Tai viena iš žmogiškos būties dalių.',
    'Saugus ryšys ne prieštarauja autonomijai, o ją stiprina.',
    'Kai jaučiu, kad esu matomas, priimamas ir svarbus kitam, man lengviau būti savimi.',
    'Suaugusiųjų prieraišumas skiriasi nuo vaiko ryšio su tėvais.',
    'Jis labiau remiasi vidiniu kito žmogaus pajautimu, seksualiniu ir emociniu artumu, abipusiu rūpesčiu bei pasirinkimu būti vienas kitam.',
    'Porų terapijoje svarbu ne tik išmokti „teisingai konfliktuoti".',
    'Kartais daug svarbiau atrasti atsakymą į klausimą: ar mes dar galime vienas kitą pasiekti?',
    'Ar tarp mūsų dar yra vietos švelnumui, ilgesiui, meilei ir gyvam susitikimui?',
    'Galbūt tikras artumas prasideda ten, kur autonomija ir ryšys ne kovoja tarpusavyje, o pradeda maitinti vienas kitą.',
  ],
};

export const article11: Article = {
  slug: 'some-reflections-on-sexuality-in-couples',
  title: 'Some reflections on sexuality in couples',
  category: 'English',
  language: 'en',
  excerpt: 'The longer I work with intimacy and relationships, the more I see that sexuality is rarely only about sex. Very often, underneath it, there is shame.',
  relatedSlugs: ['ar-mums-patogu-kalbeti-apie-seksualuma', 'kai-artumas-tampa-atrama', 'po-neistikimybes'],
  publishedAt: '2025-06-15',
  content: [
    'Some reflections on sexuality in couples.',
    'The longer I work with intimacy and relationships, the more I see that sexuality is rarely only about sex.',
    'Very often, underneath it, there is shame.',
    'Fear of rejection, of wanting too much, and fear of not being enough for the other person.',
    'Many people learned quite early that some parts of themselves are better hidden: desire, tenderness, intensity, fantasies, vulnerability.',
    'Sometimes even asking for closeness, touch, or affection can feel uncomfortable or exposing.',
    'And maybe one of the deeper questions inside sexuality is this: Can I speak about my weakness here?',
    'Can I reveal my fantasies, my longing, my tenderness?',
    'Can I allow another person to see not only my confidence, but also my uncertainty, my sensitivity, my need for closeness?',
    'I sometimes think sexuality is also the ability to touch another person from a deeper place.',
    'Not only physically, but emotionally.',
    'To open yourself.',
    'To let yourself be affected by another person.',
    'To risk being seen.',
    'I recently came across an idea from Brigitte Martel that stayed with me.',
    'She writes that healthy sexuality is not built only on attraction or passion, but on the movement between three important experiences: tenderness, closeness, and aggression.',
    'Tenderness is being able to give and receive softness, care, affection.',
    'Closeness is letting another person come near without losing yourself.',
    'And aggression is not violence, but the life energy that helps us move toward another person, express desire, take space, say yes, say no.',
    'I think many people become disconnected from this part of themselves very early.',
    'They learn that desire is selfish, dangerous, shameful, or "too much."',
    'And little by little, sexuality can become something hidden, careful, muted.',
    'This is also why conversations about intimacy in therapy can feel so vulnerable.',
  ],
};
