import type { Article } from './types';

export const article6: Article = {
  slug: 'ar-mums-patogu-kalbeti-apie-seksualuma',
  title: 'Ar mums patogu kalbėti apie seksualumą?',
  category: 'Artumas ir seksualumas',
  language: 'lt',
  excerpt: 'Seksualumas yra ta tema, nuo kurios vieniems vis dar rausta veidai, o kitiems tai atrodo visiškai natūrali kasdienybės dalis. Kiek mes iš tiesų esame nuoširdžiai atviri šioje temoje?',
  relatedSlugs: ['some-reflections-on-sexuality-in-couples', 'kai-artumas-tampa-atrama', 'po-neistikimybes'],
  publishedAt: '2025-04-01',
  content: [
    'Seksualumas yra ta tema, nuo kurios vieniems vis dar rausta veidai, o kitiems tai atrodo visiškai natūrali kasdienybės dalis.',
    'Dažnai savęs klausiu: kiek mes iš tiesų esame nuoširdžiai atviri šioje temoje? Kiek drįstame parodyti save tikrus, be kaukių?',
    'Apskritai, ką mums reiškia malonumas?',
    'Žiniasklaidoje mirga straipsniai, teigiantys, kad mylėtis sveika, kad tai mažina infarkto riziką, palaiko sveikatingumą ir yra tiesiog „reikalinga santykiams".',
    'Kita vertus, kaip retai galima rasti tekstų, kuriuose apie seksualumą kalbama kaip apie vieną giliausių poros meilės išraiškų, kaip apie artumo sąjungą.',
    'Malonumas nėra tik mechaniškas, fizinis dalykas – tai visų pirma santykio reiškinys.',
    'Šiandienos visuomenėje esame raginami eksperimentuoti, fantazuoti, ieškoti vis naujų santykio formų, būti maksimaliai laisvi.',
    'Tačiau čia slypi didysis paradoksas: būti laisvam išorėje kartais yra daug lengviau, nei atsiverti savo artimiausiam žmogui.',
    'Pasakyti, ko aš tikiuosi, kas man patinka, ir išreikšti seksualumą ne kaip galios simbolį ar pasirodymą, o kaip kūnišką meilės kalbą, einančią greta su emociniu intymumu.',
    'Terapijoje pastebiu dvi tendencijas.',
    'Vieni žmonės seksualumo temos išvis neliečia arba kalba apie ją su didele gėda.',
    'Kiti, priešingai, kalba labai atvirai, bet tame demonstratyviame atvirume taip pat jaučiasi gėda.',
    'Vyrauja jausmas, kad visuomenė mus įrėmina: „kalbėk daugiau, žinok daugiau, daryk geriau".',
    'Tačiau žodžių daug, o tikrosios, saugios išraiškos retai kada lieka.',
    'Santykiuose seksualumas niekada nėra tik apie seksą.',
    'Tai ir apie saugumą, prisirišimą, pasitikėjimą, gėdą, baimę būti atstumtam, norą būti priimtam.',
    'Tai, kaip mes mylimės, dažnai atspindi tai, kaip jaučiamės santykyje.',
    'O tai, kaip jaučiamės santykyje, neišvengiamai veikia ir mūsų seksualumą.',
    'Todėl sveikas seksualumas neatsiejamas nuo emocinio prisirišimo ir artumo.',
    'Kai santykiuose trūksta saugumo, intymumas gali virsti įrankiu įtikti, išvengti atstūmimo ar pasipuikuoti, o tai sukelia tik dar daugiau nerimo dėl savo kūno ir „pasirodymo".',
    'Tikroji laisvė intymume gimsta iš saugumo.',
    'Kai ryšys saugus, kūnas gali atsipalaiduoti, pasitikėti ir patirti prisilietimą kaip tai, kas ir jaudina, ir ramina.',
  ],
};

export const article7: Article = {
  slug: 'psichoterapeuto-uzrasai',
  title: 'Psichoterapeuto užrašai',
  subtitle: 'Psichoterapeuto užrašai: apie mažus džiaugsmus, ryšį ir buvimą išgirstam',
  category: 'Psichoterapija',
  language: 'lt',
  excerpt: 'Kartais galvoju, ką reiškia būti terapeutu. Ar tai reiškia būti tuo, kuris žino? O gal terapeutu tampama vis iš naujo: mokantis būti smalsiam, atviram, gyvam, paliestam kito žmogaus buvimo?',
  relatedSlugs: ['kai-rysys-gydo', 'ar-terapija-turi-nuraminti', 'kai-artumas-tampa-atrama'],
  publishedAt: '2025-04-15',
  content: [
    '„Dažnai neįvertiname to, ką turime, kol to neprarandame."',
    'Banali frazė. Daug kartų girdėta podcastuose, straipsniuose, pokalbiuose. Tarsi nutrinta nuo per dažno vartojimo.',
    'Ir vis dėlto ji vis dar sugeba nustebinti – ypač tada, kai pasirodo ne kaip mintis, o kaip gyvas patyrimas.',
    'Kartais galvoju, ką reiškia būti terapeutu.',
    'Ar tai reiškia būti tuo, kuris žino? Ekspertu, kuris supranta, paaiškina, veda?',
    'O gal terapeutu tampama vis iš naujo: mokantis būti smalsiam, atviram, gyvam, spontaniškam, paliestam kito žmogaus buvimo?',
    'Sėdžiu terapijos kabinete. Kalbamės su kliente apie sunkumus, priklausomybę, apie laikotarpį, kuriame po truputį atsiranda daugiau erdvės gyventi.',
    'Ir staiga ji pradeda pasakoti apie mažus dalykus.',
    'Apie žydinčias gėles.',
    'Apie paukščių čiulbėjimą.',
    'Apie gamtos niuansus, kurių anksčiau tarsi nematė.',
    'Tai atrodo paprasta. Tačiau kartu labai daug.',
    'Kūnas ir smegenys nebe taip desperatiškai ieško staigaus dopamino šuolio. Atsiranda galimybė pastebėti tylų, lėtą, kasdienį džiaugsmą.',
    'Mes sustojame prie to. Tyrinėjame. Pabūname jos džiaugsmo akimirkose, kurios kažkaip ima nuspalvinti ir mano paties gyvenimą.',
    'Aš šypsausi ir sakau:',
    '„Žinai, man gera tai girdėti. Jaučiu šilumą krūtinėje, kai tu kalbi apie šiuos mažus džiaugsmus. Norisi kartu juos išgyventi."',
    'Ji išgirsta. Jos veidas dar labiau atsipalaiduoja.',
    'Ir tada vėl pagalvoju, kaip gera žmogui būti išgirstam. Tarsi išgirstas džiaugsmas gauna daugiau vietos. Tarsi jis tampa tikresnis, kai gali būti paliudytas kito.',
    'Sue Johnson, emocijų terapijos kūrėja, yra sakiusi, kad žmonės yra „wired for connection" – sukurti ryšiui.',
    'Tokiais momentais tai nebe teorija. Tai vyksta čia pat, tarp dviejų žmonių.',
    'Mano veidas švyti. Klientė skleidžiasi.',
    'Po kurio laiko ji prisimena žmogų, kuris ją palaiko gyvenime. Santykį, kuriame yra daug rūpesčio, meilės ir buvimo šalia.',
    'Jaučiu, kaip mano kūnas rezonuoja į tą šilumą. Sakau:',
    '„Jaučiu tokį šviesų, gražų jausmą girdėdamas apie tokį palaikantį ryšį. Gera žinoti, kad tavo gyvenime yra žmogus, su kuriuo yra tiek meilės, palaikymo."',
    'Jos veide atsiranda švelnumas. Ji atsipalaiduoja krėsle.',
    'Intymus momentas – dvi būtys prisimena apie jas palietusius žmones ir tuo pat metu dalijasi tuo čia, terapijos kabinete.',
    'Mes tylime.',
    'Pro langą pradedu girdėti paukščių čiulbėjimą. Ji pasako apie vėjo garsą.',
    'Ar įmanoma sustoti?',
    'Man atrodo, kad terapija kartais ir yra vieta, kur galima sustoti.',
    'Vieta, kur kitas žmogus savo buvimu pakviečia tave pastebėti: štai, tai vyksta dabar. Štai, gyvenimas dar yra čia.',
    'Gera suprasti, kad nebūtina laukti praradimo, jog pajustum, kiek svarbus tau yra žmogus.',
    'Kartais tai supranti būdamas terapeutu su kitu. Klausydamas kito žmogaus, staiga prisimeni ir savo gyvenimą. Savo artimus. Savo pamirštą dėkingumą.',
    'Klientė tyliai pasako:',
    '„O aš jam dar niekada tiesiai nepasakiau, kiek jis man svarbus."',
    'Pakviečiu ją pabandyti tai pasakyti dabar:',
    '„Tu man svarbus. Aš dėkinga, kad esi mano gyvenime."',
    'Ji ištaria šiuos žodžius. Jos akyse pasirodo ašaros.',
    'Susitikimas palietė, pasiėmęs telefoną į rankas parašiau:',
    '„Myliu tave. Ir vertinu, kad esi mano gyvenime."',
  ],
};

export const article8: Article = {
  slug: 'gedulas-ir-kalte',
  title: 'Apie gedėjimą ir kaltę',
  category: 'Gedėjimas',
  language: 'lt',
  excerpt: 'Kartais, netekus svarbaus žmogaus ar ryšio, skauda ne tik dėl pačios netekties. Skauda ir dėl balsų, kurie atsiranda aplink ją: ar tikrai padariau viską, ką galėjau? Viena skaudžiausių dalykų sielvarte yra tai, kad žmogus kartais nebegali tiesiog liūdėti.',
  relatedSlugs: ['kai-rysys-gydo', 'ar-terapija-turi-nuraminti', 'kai-artumas-tampa-atrama'],
  publishedAt: '2025-05-01',
  content: [
    'Kartais, netekus svarbaus žmogaus ar ryšio, skauda ne tik dėl pačios netekties.',
    'Skauda ir dėl balsų, kurie atsiranda aplink ją:',
    'Ar tikrai padariau viską, ką galėjau?',
    'Kodėl nepastebėjau anksčiau?',
    'Kaip gyventi toliau su tuo, kas liko nepasakyta?',
    'Tada liūdesiui tarsi nebelieka vietos. Vietoje jo atsiranda kaltė, savęs vertinimas, bandymas suprasti, kur buvo klaida.',
    'Man atrodo, vienas skaudžiausių dalykų sielvarte yra tai, kad žmogus kartais nebegali tiesiog liūdėti.',
    'Jis turi gintis – nuo savo minčių, nuo aplinkos, nuo vidinių kaltinimų.',
    'Tarsi neužtenka to, kad skauda.',
    'Dar reikia įrodyti, kad mylėjai pakankamai, stengeisi pakankamai, buvai pakankamai geras.',
    'Aplinka, norėdama padėti, kartais skuba pasakyti: „būk stiprus", „laikas gydo", „žiūrėk pozityviai", „reikia gyventi toliau", „viskas vyksta dėl priežasties".',
    'Bet tokie žodžiai dažnai nepalengvina gedėjimo – jie nutildo tai, kas dar nori būti išsakyta.',
    'Sielvartui dažnai reikia ne paaiškinimų, ne patarimų ir ne bandymo parodyti „šviesiąją pusę".',
    'Jam reikia erdvės ištarti:',
    'man skauda dėl to, ko netekau.',
    'aš ilgiuosi to, kas buvo.',
    'aš pykstu, kad viskas pasikeitė.',
    'man gaila to, kas liko nepasakyta.',
    'aš nežinau, kaip būti su tuo, ko nebėra.',
    'Gedėjimui ir paleidimui reikalingas Kitas – žmogus, kuris gali būti kartu, girdėti, švelniai palaikyti ir tapti šio skausmo liudytoju.',
    'Kartais labiausiai padeda ne tobuli žodžiai, o paprastas buvimas:',
    '„Aš nežinau, ką dabar pasakyti, bet galiu būti su tavimi."',
    '„Gali nekalbėti – aš pabūsiu kartu."',
    '„Tavo gedėjimas neturi termino."',
    'Man atrodo, jog svarbu nelikti vienam su tuo skausmu, nes gedėjimas nėra silpnumas, o geba atverti savo žaizdas ir leisti joms pagyti Kito akivaizdoje.',
    'Tos žaizdos ir galiausiai jų vietoje atsiradę randai liudija, jog kažkas buvo svarbaus: ryšys, meilė, prisirišimas, istorija...',
  ],
};
